###
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,... 
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.
###

def main():
    limit = 4_000_000
    fibs = [1, 2]
    sum = 2 # subtract the 2, is even
    i = 0
    
    while True:
        f = fibs[i] + fibs[i + 1]
        if (f < limit):
            fibs.append(f)
            if (f % 2) == 0:
                sum += f 
            i += 1
        else: 
            break

    print("solution: " + str(sum))

if __name__ == "__main__":
    main()